### PR TITLE
Add --force option to knife acl add to override best practice

### LINKED ISSUE #37: Add force switch to override best practice restrictions
Some users for internal reasons may wish to ignore the best practices and add users to an ACL.

Best practices are fine, but the tools should not get in the way of performing what is required when it is supported by the underlying system.

A --force switch should be added to knife-acl to allow override of the best practise restriction.

### PR DESCRIPTION
**Pull request by drrk**
Fixes #37

### CODE REVIEW

**Comment by stevendanna** [comment]
I'm 👍. @jeremiahsnapp thoughts?

**Comment by jeremiahsnapp** [comment]
Sounds great. @drrk can you also add that to acl_bulk_add.rb please?

**Comment by tas50** [comment]
@drrk Any chance you can finish this PR up so we can ship it?

**Comment by tas50** [comment]
Closing this out since we never heard back

**Pull request closed without merging**
