### PR TITLE
Fix for private chef group add actor for 'user'

### PR DESCRIPTION
**Pull request by jtolsma**
Private chef bombs on the ID for users and the fact it wants to check on clients/groups.  Not sure if this is the right way to do this, but it works for our private chef installation.  Current knife-acl bomps like so for 'knife group add actor admins username':

INFO: HTTP Request Returned 500 Internal Server Error: Client pivotal does not exist
ERROR: Server returned error for https://chefserver/organizations/infrastructure-56m/groups/admins, retrying 3/5 in 13s

If I just remove the clients section, I get:
INFO: HTTP Request Returned 500 Internal Server Error: Users 3029dc16617811e298d590b11c089a5b do not exist
ERROR: Server returned error for https://chefserver/organizations/infrastructure-56m/groups/admins, retrying 1/5 in 4s

It seems private chef wants the username, not the ID?  This works well against a test installation, but wanted to get an official review before using it.

### CODE REVIEW

**Comment by thommay** [comment]
@jtolsma hi, we'd love to get this Pull Request merged, but as Seth said a couple of years ago we need you to sign our Contributor License Agreement (CLA). There are a lot more [details](http://docs.chef.io/community_contributions.html) on our documentation site.

**Comment by jtolsma** [comment]
Hi thommay, is this still applicable to newer versions of private chef servers?  I have not used it since 2013 and cannot test it.

**Comment by stevendanna** [comment]
@thommay @jtolsma We likely want to make sure this is fixed in the improvements @jeremiahsnapp has worked on here: https://github.com/chef/knife-acl/pull/19

**Comment by jeremiahsnapp** [comment]
Hello @jtolsma thanks a lot for your PR. Sorry it's been overlooked for such a long time. knife-acl hasn't received a lot of attention until recently. I recently made some significant changes/improvements to knife-acl and released them as version 1.0.0.beta. I'm not having any problems adding users to groups using the following command syntax.

```
knife group add user test-user admins
```

If you or anyone else if still having problems adding users to groups using the 1.0.0.beta version please let me know. In the meantime I'm going to close this PR

**Pull request closed without merging**
